### ISSUE TITLE
GUI 

### ISSUE THREAD

**Issue by ybs5050** [CMPSC221/Schedule-Application#7]
So.... I guess we need to make a  GUI panel that has
> Use a single window separated into different areas for class management, instructor management, schedule management, etc.
Use a main window for the schedule management and pop-up windows for the instructors and courses.
Use a tabbed pane

I know how to do this in Netbeans IDE with Swing but we are sticking with JavaFX right?
Where do we start?

**Comment by RobertBColton** [comment]
I finished reading the chapter on JDBC and it seems that using JavaFX would basically come out the same.
http://www.swtestacademy.com/database-operations-javafx/

The advantages to using JavaFX include the data binding and streams and that we can put our layout code in a layout file. This makes our code easier to read in my opinion as we just put it in a separate file and then add the code in the controller.

I don't care either way, I will let you guys decide, but I sent an email to the professor last night whether he decided if we can use JavaFX. He still never answered my original email.

**Comment by bfid111** [comment]
JavaFX is fine with me as long as the Professor is okay with it.

**Comment by RobertBColton** [comment]
Alright I got his response:

> Robert,
> 
> Right, sorry. I think it will be fine. My concerns stem more from my limited familiarity with JavaFX so this might be a good experiment.
> 
> -- Hal 

So I guess we're all set to use JavaFX. Would you guys like me to set it up?

**Comment by RobertBColton** [comment]
Alright in #8 I have set up JavaFX. I would appreciate if you guys could look it over to make sure you are comfortable with it first.

**Comment by bfid111** [comment]
Ok, It doesn't seem that different than Swing. I think I would do fine working with it. Thanks for setting it up @RobertBColton

**Comment by RobertBColton** [comment]
Yeah you can see it's a lot like building a web page, easy peasy. The reason why this is a lot more popular is the code is easier to read since everything is separated. It makes it less likely that git conflicts will occur when multiple people work on a project too. WPF/Windows Presentation Foundation is very similar.

**Comment by bfid111** [comment]
BTW, don't we have another team member? Where is he?

**Comment by RobertBColton** [comment]
I think so and I am not sure.

**Comment by bfid111** [comment]
GitHub Name is LavenderM. I sent an invite but no answer.

**Comment by bfid111** [comment]
Is It okay if I submit the assignment for this week?
@RobertBColton

**Comment by RobertBColton** [comment]
I was hoping we'd actually add some of the buttons and something to the tabs. It's hard to decide at this point without having a better idea what the project is supposed to end up like. Honestly I feel he could have described things a little better.

**Comment by bfid111** [comment]
I think we have what he listed, assuming that that is all we need for the GUI. But it is true that we will need more buttons.

**Comment by RobertBColton** [comment]
I'll add a couple more things here in a second and send a PR and then we can submit it.

**Comment by bfid111** [comment]
Sounds good

**Comment by RobertBColton** [comment]
I'm working on #9 and I am still trying to think but it's difficult because he doesn't give us much to go on with the classes in order to know what our UI would even look like. It's bugging me because I don't know what this is going to end up like.

**Comment by bfid111** [comment]
![image](https://cloud.githubusercontent.com/assets/15918225/15995017/1a51ab30-30e1-11e6-841e-66b5b72443f3.png)

So, the "New" Button should add a new class? I'm kinda lost here.

**Comment by RobertBColton** [comment]
No I don't know what the new button should do. I was just using it as a place holder. I am lost too as I said because he does not provide much direction. I feel like it should look more like the books examples in the JDBC chapter.

**Comment by bfid111** [comment]
https://github.com/CMPSC221/Schedule-Application/pull/11

I guess it would look similar to this to add a new section? Sorry for the poor design, JavaFX is still really new to me. I  taking all the necessary information (name,time,abbrevation), and add it to the database directly would work possibly.

**Comment by RobertBColton** [comment]
Yes, I was thinking like the books examples.

![Book Database GUI](https://cloud.githubusercontent.com/assets/3212801/15995747/fb71726a-30ed-11e6-9348-fe65fd550afa.png)

Please see my comments on #11 as I wanted to try to help you a little bit with understanding git so you don't have to manually remake all the changes.

**Comment by bfid111** [comment]
> For this milestone, submit your SQL scripts used to create your database tables.

Does this mean we need to create a SQL file?

**Comment by bfid111** [comment]
![1](https://cloud.githubusercontent.com/assets/15918225/16212489/070aed80-3716-11e6-8e63-f9a6e3b6307c.jpg)
![2](https://cloud.githubusercontent.com/assets/15918225/16212491/0710c520-3716-11e6-8de6-99f16bc9a1aa.jpg)
![3](https://cloud.githubusercontent.com/assets/15918225/16212490/070d2f64-3716-11e6-816c-0e91c210c40d.jpg)


I created a basic script for saving classes and instructor information

**Comment by RobertBColton** [comment]
Do we still need anything else for the SQL milestone?

This is now where we can replace the AtomicInteger thing using pure Oracle flaored SQL to generate the unique id with AUTO INCREMENT.
http://stackoverflow.com/questions/11296361/how-to-create-id-with-auto-increment-on-oracle

I think we may also want to make a meetings table so we can have a many to many relationship between meeting times and classes. Classes sometimes meet on different start and end times at certain days of the week. For that we just need a foreign key:
```sql
/*classes*/
DROP TABLE IF EXISTS `classes`;
CREATE TABLE `classes` (
  `course id` int(64) NOT NULL,
  `course name` text NOT NULL,
  `course abbreviation` text NOT NULL,
  PRIMARY KEY (`course id`)
);

/*meetings*/
DROP TABLE IF EXISTS `meetings`;
CREATE TABLE `meetings` (
  `meeting id` int(64) NOT NULL,
  `start time` time NOT NULL,
  `end time` time NOT NULL,
  `M` bool null,
  `T` bool null,
  `W` bool null,
  `TR` bool null,
  `F` bool null,
  PRIMARY KEY (`meeting id`),
);

/*classmeetings*/
DROP TABLE IF EXISTS `classmeetings`;
CREATE TABLE `classmeetings` (
  `meeting id` int(64) NOT NULL,
  `course id` int(64) NOT NULL,
  FOREIGN KEY (`meeting id`) REFERENCES meetings(`meeting id`),
  FOREIGN KEY (`course id`) REFERENCES classes(`course id`)
  PRIMARY KEY (`meeting id`, `course id`),
);
```

**Comment by bfid111** [comment]
No, just a single script will be good enough.
But we only have two weeks left in this course and I wonder if the prof expects us to finish this whole thing in time

**Comment by RobertBColton** [comment]
I was wondering the same thing myself but I am starting to think he doesn't expect us to.

**Comment by bfid111** [comment]
btw, it turns out that we do have another group member, and he has been receiving the same grade that we got when he haven't wrote a single line of code for the past month and a half. Makes me kinda mad. Should I take this to the prof?

**Comment by RobertBColton** [comment]
Well, I mean, you are right and I hate that this sort of thing always comes up in group projects. Normally I try to make one last attempt to contact the team member first, but he should already be getting these notifications from being in this group. I think we should try sending him a message directly on Canvas or his PSU email first. How's that sound?

**Comment by bfid111** [comment]
I mean, I already contacted him vefore through canvas before, asking him to start working on things and he said that he will start contributing but it has been  what 6 weeks and he didnt even join the group. i just cant be okay with someone taking credit when that person literally didnt do anything.

**Comment by RobertBColton** [comment]
Oh ok, you didn't tell me that before. I would say to go ahead then and tell the professor.

**Comment by bfid111** [comment]
![1](https://cloud.githubusercontent.com/assets/15918225/16408860/af1b986c-3ce8-11e6-8722-f3324348e1be.jpg)

Yup, I sent this message 2 weeks ago. 

plus 

> The course evaluation will be based on the following elements

Project Milestones:	40%
Final Project:	60%


I'm pretty sure we will have to make this schedule application work.
My assumption is that we manually add courses that needs to be taught and make the application automatically assign it to the instructor if possible and save it to db? I will ask this to the prof for clarification

**Comment by RobertBColton** [comment]
Yeah sounds good and I don't think there's anything else you can do to get him to contribute either.

**Comment by ybs5050** [comment]
I sent him an email saying that it is unfair that the other group member received the same grade when that person did absolutely nothing, and he should not receive credit for the past assignments; and he should no longer be in our group as he doesn't care his group members nor the project. 
I hate to be the "snitch" but I did what I had to do

**Comment by LavenderM** [comment]
I am really sorry. I want to work on the final project but I am quite behind. I feel so ashamed of myself but is there anything I can do right now?

**Comment by ybs5050** [comment]
Go through everything we have so far so you can start contributing when the prof gives us the next assignment. Good that you are finally here

**Comment by RobertBColton** [comment]
The class is now ending, look at the schedule of topics:
04-jul | Overflow/Wrap-Up

If you go on eLion the last day of this class is July 8th under the "Student Schedule"

**Comment by ybs5050** [comment]
So, what do we do now then?

**Comment by RobertBColton** [comment]
Ok yeah he just graded us for the last milestone, so with all A's so far we have a 40% overall for the class. The last submission is 60% of our grade. He can help us with the final submission then which the professor has opened and due for the 8th.

**Comment by ybs5050** [comment]
Okay, first I will work on adding courses to be taught to the db. I will post an update in the next couple hours.

**Comment by ybs5050** [comment]
Okay, I finished the database connection portion and adding a new course to db. 
This is how it looks like when you add a new course.
![1](https://cloud.githubusercontent.com/assets/15918225/16636638/6dda9c70-43a7-11e6-938d-6ddb8486e1b1.jpg)
![1_00000](https://cloud.githubusercontent.com/assets/15918225/16636637/6dd9f0d6-43a7-11e6-8c94-7638be782667.jpg)
![1_00002](https://cloud.githubusercontent.com/assets/15918225/16636636/6dd6fc96-43a7-11e6-898e-4a594f7cab45.jpg)

I just put the add section GUI part in the same panel to make it simpler.
I'm using MySQL Server and Broswer to view the sql. I will give you a link to download. 
https://drive.google.com/file/d/0B3ad9D8LwoprRXF4QkpqclEwMVk/view?usp=sharing
l used 'root' for both login id and pw. you can always change them in the Database class if you need to.
Now we need to work on creating the schedule by fetching courses from db.

**Comment by RobertBColton** [comment]
Cool beans, pick something random for me and him each to do and let me know.

**Comment by ybs5050** [comment]
First, try to set up the MySQL Server and Browser and see if "AddSection" Tab works in your computer too. @RobertBColton  You need to set your mysql id and pw to "root" when you install the software. 
If everything works, could you work on printing the list of courses that are added to db on "Sections" tab? or you could start working on schedule auto-generation part. 
@LavenderM  You need to first understand the overall idea of the project. After that, you could help us do the schedule auto-generation part since that will take the most time. 

I will start working on more things tomorrow, I gtg sleep.

**Comment by LavenderM** [comment]
Thank you and sorry again. Actually I replied the prof's email last week and now I am not in the team anymore. I will complete my final project on my own and submit separately. Sorry for doing nothing in this team and I know there is no excuse for me. Good luck on your final project.

**Comment by ybs5050** [comment]
@RobertBColton 
So, in[Database class](https://github.com/CMPSC221/Schedule-Application/blob/master/src/edu/psu/teamone/main/Database.java), I created a method that loads section and meeting data from db and save them in to as ArrayList<Section> and ArrayList<Meeting>in [Controller class](https://github.com/CMPSC221/Schedule-Application/blob/master/src/edu/psu/teamone/main/Controller.java)

I need you to somehow make the data loded show on the ViewTable.
All methods like `getStarTime(), getEndTime(), getName(),` etc works. 
like say that there is variable called `ArrayList<Section> sections` in Controller class. 
you can get the name of first section in db by `String blahblah = sections.get(0).getName();`

So, we have two arraylists sections and meetings. Now we need to somehow print the data (course name, abbreviation, start time,end time, days) on the table.

I'm going to work on section editing and instructor editing tonight

**Comment by RobertBColton** [comment]
Yeah that sounds fine I can do that part because that was exactly what I was reading about the other day and wanted to use JavaFX for. Let me do my discussion post for math and then I'll get started.

**Comment by ybs5050** [comment]
Sounds good, once that is done, all we have left to do is the auto-generation part and create an output like an excel file. I'll work as much as I can today and see how it goes

**Comment by ybs5050** [comment]
I've added deleteSection function. 
It works find and I'm going to work on adding,deleting,editing instructor and editing section.

**Comment by ybs5050** [comment]
crap I messed up
`void getDataFromDB(ArrayList<Section> section, ArrayList<Meeting> meeting)` in Database class supposed to change `ArrayList<Section> section` and ` ArrayList<Meeting> meeting` value.
But it turns out that the changed value doesn't get passed.
What other ways are there to change two passed in variables?

**Comment by ybs5050** [comment]
Never mind, I've just created two separate methods to load data. Everything is find now

**Comment by RobertBColton** [comment]
Classes/objects in Java are pass by reference, when you pass them they are passed as a reference, so it is the original object you are modifying. Primitive types like int, boolean, float, and double are pass by value so you have to return the new value.

**Comment by ybs5050** [comment]
yeah, I got confused with C++. What a silly mistake.
I've just finished edit section and delete function.
Hows the ViewTable going?

**Comment by ybs5050** [comment]
Okay, heres what works at does not work right now.

Things that work
- Adding new class section
- Adding new instructor
- Editing/Deleting sections and instructors

What needs to be done
- Printing sections on the viewtable
- Auto generate schedule based on the sections from db and save them as an excel file.

Auto generate part wouldn't be that hard if we just make it sorted by section time and see if it is possible to crank all the sections.

Anyways, I think it's safe to say that we're almost done.
Just in case you don't have access to mysql,
here is a video of how it looks when the program runs right now
https://drive.google.com/drive/my-drive

**Comment by RobertBColton** [comment]
Ok I downloaded and ran both of the installers fine but neither of them asked me for a password or username. I pulled the latest commits and I get the following error when building:
```
Description	Resource	Path	Location	Type
Project 'Schedule-Application' is missing required library: 'libs/mysql-connector-java-bin.jar'	Schedule-Application		Build path	Build Path Problem
```
Where did you get that library from? Do I need to copy and paste it?

**Comment by ybs5050** [comment]
You need to open mysql server instance configuration wizard to set password i think. Are you able to open the sql browser? The library is in libs folder. Just add the jar file to the project build path.
![1](https://cloud.githubusercontent.com/assets/15918225/16698022/54f8ae44-451a-11e6-8edb-70a78d27e2ed.jpg)

**Comment by ybs5050** [comment]
oops. I gave you a wrong link.
https://drive.google.com/file/d/0B3ad9D8Lwoprc2FWc25XWmpjMms/view?usp=sharing

this is how it looks right now

**Comment by RobertBColton** [comment]
Ok I got that far but then when I hit ok after filling it out it won't connect.
![wontconnect](https://cloud.githubusercontent.com/assets/3212801/16698459/523a13a8-451c-11e6-9d33-5ce1098c248c.png)

Also which libs folder? A local folder to the project or in the MySQL installation directory?

**Comment by ybs5050** [comment]
https://github.com/CMPSC221/Schedule-Application/tree/master/libs
this folder.
you need to use "root" as password too.
if that doesn't work, go to start, and search for mysql server instance configuration wizard.
press next until you see 
![1](https://cloud.githubusercontent.com/assets/15918225/16698593/0ff9049e-451d-11e6-9838-4b59de63b88f.jpg)

and use root for all three boxes and press next and press execute

**Comment by ybs5050** [comment]
![1](https://cloud.githubusercontent.com/assets/15918225/16698642/540e7ede-451d-11e6-9a6d-1f8615b47bfd.jpg)

use root for your password.
Are you sure the install never prompted for a password or username?

**Comment by ybs5050** [comment]
you can add me on skype 

> nnod111

if you need to chat with me

**Comment by RobertBColton** [comment]
That worked, I got it now, and no it did not prompt me.

**Comment by RobertBColton** [comment]
I am closing this since we are on Skype now and we can post new tickets for other issues.
